/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Onboarding.Net.Api;
using Splitit.Onboarding.Net.Model;
using Splitit.Onboarding.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Onboarding.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMerchantResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMerchantResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMerchantResponse
        //private CreateMerchantResponse instance;

        public CreateMerchantResponseTests()
        {
            // TODO uncomment below to create an instance of CreateMerchantResponse
            //instance = new CreateMerchantResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMerchantResponse
        /// </summary>
        [Fact]
        public void CreateMerchantResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMerchantResponse
            //Assert.IsType<CreateMerchantResponse>(instance);
        }


        /// <summary>
        /// Test the property 'MerchantTempId'
        /// </summary>
        [Fact]
        public void MerchantTempIdTest()
        {
            // TODO unit test for the property 'MerchantTempId'
        }
        /// <summary>
        /// Test the property 'MerchantStatus'
        /// </summary>
        [Fact]
        public void MerchantStatusTest()
        {
            // TODO unit test for the property 'MerchantStatus'
        }
        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

    }

}
