/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Onboarding.Net.Api;
using Splitit.Onboarding.Net.Model;
using Splitit.Onboarding.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Onboarding.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateDeveloperRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateDeveloperRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateDeveloperRequest
        //private CreateDeveloperRequest instance;

        public CreateDeveloperRequestTests()
        {
            // TODO uncomment below to create an instance of CreateDeveloperRequest
            //instance = new CreateDeveloperRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateDeveloperRequest
        /// </summary>
        [Fact]
        public void CreateDeveloperRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateDeveloperRequest
            //Assert.IsType<CreateDeveloperRequest>(instance);
        }


        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'TermsAndConditions'
        /// </summary>
        [Fact]
        public void TermsAndConditionsTest()
        {
            // TODO unit test for the property 'TermsAndConditions'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'FullCountryName'
        /// </summary>
        [Fact]
        public void FullCountryNameTest()
        {
            // TODO unit test for the property 'FullCountryName'
        }
        /// <summary>
        /// Test the property 'RequestHeader'
        /// </summary>
        [Fact]
        public void RequestHeaderTest()
        {
            // TODO unit test for the property 'RequestHeader'
        }

    }

}
