/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Onboarding.Net.Api;
using Splitit.Onboarding.Net.Model;
using Splitit.Onboarding.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Onboarding.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CurrenciesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrenciesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CurrenciesResponse
        //private CurrenciesResponse instance;

        public CurrenciesResponseTests()
        {
            // TODO uncomment below to create an instance of CurrenciesResponse
            //instance = new CurrenciesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CurrenciesResponse
        /// </summary>
        [Fact]
        public void CurrenciesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CurrenciesResponse
            //Assert.IsType<CurrenciesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Fact]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }

    }

}
