/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Onboarding.Net.Api;
using Splitit.Onboarding.Net.Model;
using Splitit.Onboarding.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Onboarding.Net.Test.Model
{
    /// <summary>
    ///  Class for testing GetMerchantsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMerchantsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMerchantsResponse
        //private GetMerchantsResponse instance;

        public GetMerchantsResponseTests()
        {
            // TODO uncomment below to create an instance of GetMerchantsResponse
            //instance = new GetMerchantsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMerchantsResponse
        /// </summary>
        [Fact]
        public void GetMerchantsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMerchantsResponse
            //Assert.IsType<GetMerchantsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Merchants'
        /// </summary>
        [Fact]
        public void MerchantsTest()
        {
            // TODO unit test for the property 'Merchants'
        }

    }

}
