/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Onboarding.Net.Api;
using Splitit.Onboarding.Net.Model;
using Splitit.Onboarding.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Onboarding.Net.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessorResponse
        //private ProcessorResponse instance;

        public ProcessorResponseTests()
        {
            // TODO uncomment below to create an instance of ProcessorResponse
            //instance = new ProcessorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessorResponse
        /// </summary>
        [Fact]
        public void ProcessorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessorResponse
            //Assert.IsType<ProcessorResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProcessorAuthenticationParametersRequest'
        /// </summary>
        [Fact]
        public void ProcessorAuthenticationParametersRequestTest()
        {
            // TODO unit test for the property 'ProcessorAuthenticationParametersRequest'
        }

    }

}
