/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.splitit.client.JSON;

/**
 * CreateMerchantResponse
 */
@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateMerchantResponse {
  public static final String SERIALIZED_NAME_MERCHANT_TEMP_ID = "merchantTempId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_TEMP_ID)
  private String merchantTempId;

  public static final String SERIALIZED_NAME_MERCHANT_STATUS = "merchantStatus";
  @SerializedName(SERIALIZED_NAME_MERCHANT_STATUS)
  private String merchantStatus;

  public CreateMerchantResponse() {
  }

  public CreateMerchantResponse merchantTempId(String merchantTempId) {
    
    this.merchantTempId = merchantTempId;
    return this;
  }

   /**
   * Get merchantTempId
   * @return merchantTempId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getMerchantTempId() {
    return merchantTempId;
  }


  public void setMerchantTempId(String merchantTempId) {
    this.merchantTempId = merchantTempId;
  }


  public CreateMerchantResponse merchantStatus(String merchantStatus) {
    
    this.merchantStatus = merchantStatus;
    return this;
  }

   /**
   * Get merchantStatus
   * @return merchantStatus
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getMerchantStatus() {
    return merchantStatus;
  }


  public void setMerchantStatus(String merchantStatus) {
    this.merchantStatus = merchantStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMerchantResponse createMerchantResponse = (CreateMerchantResponse) o;
    return Objects.equals(this.merchantTempId, createMerchantResponse.merchantTempId) &&
        Objects.equals(this.merchantStatus, createMerchantResponse.merchantStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantTempId, merchantStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMerchantResponse {\n");
    sb.append("    merchantTempId: ").append(toIndentedString(merchantTempId)).append("\n");
    sb.append("    merchantStatus: ").append(toIndentedString(merchantStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("merchantTempId");
    openapiFields.add("merchantStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("merchantTempId");
    openapiRequiredFields.add("merchantStatus");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateMerchantResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateMerchantResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateMerchantResponse is not found in the empty JSON string", CreateMerchantResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CreateMerchantResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateMerchantResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateMerchantResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("merchantTempId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantTempId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantTempId").toString()));
      }
      if (!jsonObj.get("merchantStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantStatus").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateMerchantResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateMerchantResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateMerchantResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateMerchantResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateMerchantResponse>() {
           @Override
           public void write(JsonWriter out, CreateMerchantResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateMerchantResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateMerchantResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateMerchantResponse
  * @throws IOException if the JSON string is invalid with respect to CreateMerchantResponse
  */
  public static CreateMerchantResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateMerchantResponse.class);
  }

 /**
  * Convert an instance of CreateMerchantResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

