/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.splitit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.splitit.client.model.ProcessorAuthenticationParametersRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.splitit.client.JSON;

/**
 * ProcessorResponse
 */
@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProcessorResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PROCESSOR_AUTHENTICATION_PARAMETERS_REQUEST = "processorAuthenticationParametersRequest";
  @SerializedName(SERIALIZED_NAME_PROCESSOR_AUTHENTICATION_PARAMETERS_REQUEST)
  private List<ProcessorAuthenticationParametersRequest> processorAuthenticationParametersRequest = new ArrayList<>();

  public ProcessorResponse() {
  }

  public ProcessorResponse id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public ProcessorResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ProcessorResponse processorAuthenticationParametersRequest(List<ProcessorAuthenticationParametersRequest> processorAuthenticationParametersRequest) {
    
    this.processorAuthenticationParametersRequest = processorAuthenticationParametersRequest;
    return this;
  }

  public ProcessorResponse addProcessorAuthenticationParametersRequestItem(ProcessorAuthenticationParametersRequest processorAuthenticationParametersRequestItem) {
    this.processorAuthenticationParametersRequest.add(processorAuthenticationParametersRequestItem);
    return this;
  }

   /**
   * Get processorAuthenticationParametersRequest
   * @return processorAuthenticationParametersRequest
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<ProcessorAuthenticationParametersRequest> getProcessorAuthenticationParametersRequest() {
    return processorAuthenticationParametersRequest;
  }


  public void setProcessorAuthenticationParametersRequest(List<ProcessorAuthenticationParametersRequest> processorAuthenticationParametersRequest) {
    this.processorAuthenticationParametersRequest = processorAuthenticationParametersRequest;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessorResponse processorResponse = (ProcessorResponse) o;
    return Objects.equals(this.id, processorResponse.id) &&
        Objects.equals(this.name, processorResponse.name) &&
        Objects.equals(this.processorAuthenticationParametersRequest, processorResponse.processorAuthenticationParametersRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, processorAuthenticationParametersRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessorResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    processorAuthenticationParametersRequest: ").append(toIndentedString(processorAuthenticationParametersRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("processorAuthenticationParametersRequest");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("processorAuthenticationParametersRequest");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProcessorResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProcessorResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProcessorResponse is not found in the empty JSON string", ProcessorResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ProcessorResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProcessorResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProcessorResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("processorAuthenticationParametersRequest").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `processorAuthenticationParametersRequest` to be an array in the JSON string but got `%s`", jsonObj.get("processorAuthenticationParametersRequest").toString()));
      }

      JsonArray jsonArrayprocessorAuthenticationParametersRequest = jsonObj.getAsJsonArray("processorAuthenticationParametersRequest");
      // validate the required field `processorAuthenticationParametersRequest` (array)
      for (int i = 0; i < jsonArrayprocessorAuthenticationParametersRequest.size(); i++) {
        ProcessorAuthenticationParametersRequest.validateJsonObject(jsonArrayprocessorAuthenticationParametersRequest.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProcessorResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProcessorResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProcessorResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProcessorResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProcessorResponse>() {
           @Override
           public void write(JsonWriter out, ProcessorResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProcessorResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProcessorResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProcessorResponse
  * @throws IOException if the JSON string is invalid with respect to ProcessorResponse
  */
  public static ProcessorResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProcessorResponse.class);
  }

 /**
  * Convert an instance of ProcessorResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

