/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateMerchantResponse
 */
public class CreateMerchantResponseTest {
    private final CreateMerchantResponse model = new CreateMerchantResponse();

    /**
     * Model tests for CreateMerchantResponse
     */
    @Test
    public void testCreateMerchantResponse() {
        // TODO: test CreateMerchantResponse
    }

    /**
     * Test the property 'merchantTempId'
     */
    @Test
    public void merchantTempIdTest() {
        // TODO: test merchantTempId
    }

    /**
     * Test the property 'merchantStatus'
     */
    @Test
    public void merchantStatusTest() {
        // TODO: test merchantStatus
    }

}
