/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.splitit.client.model.MerchantVerticalResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantVerticalsResponse
 */
public class MerchantVerticalsResponseTest {
    private final MerchantVerticalsResponse model = new MerchantVerticalsResponse();

    /**
     * Model tests for MerchantVerticalsResponse
     */
    @Test
    public void testMerchantVerticalsResponse() {
        // TODO: test MerchantVerticalsResponse
    }

    /**
     * Test the property 'merchantVerticals'
     */
    @Test
    public void merchantVerticalsTest() {
        // TODO: test merchantVerticals
    }

}
