/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryResponse
 */
public class CountryResponseTest {
    private final CountryResponse model = new CountryResponse();

    /**
     * Model tests for CountryResponse
     */
    @Test
    public void testCountryResponse() {
        // TODO: test CountryResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'isoA2'
     */
    @Test
    public void isoA2Test() {
        // TODO: test isoA2
    }

    /**
     * Test the property 'isoA3'
     */
    @Test
    public void isoA3Test() {
        // TODO: test isoA3
    }

    /**
     * Test the property 'isoNumber'
     */
    @Test
    public void isoNumberTest() {
        // TODO: test isoNumber
    }

}
