/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateMerchantRequest
 */
public class CreateMerchantRequestTest {
    private final CreateMerchantRequest model = new CreateMerchantRequest();

    /**
     * Model tests for CreateMerchantRequest
     */
    @Test
    public void testCreateMerchantRequest() {
        // TODO: test CreateMerchantRequest
    }

    /**
     * Test the property 'publicName'
     */
    @Test
    public void publicNameTest() {
        // TODO: test publicName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'countryIso2'
     */
    @Test
    public void countryIso2Test() {
        // TODO: test countryIso2
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'businessStreetAddress'
     */
    @Test
    public void businessStreetAddressTest() {
        // TODO: test businessStreetAddress
    }

    /**
     * Test the property 'businessCity'
     */
    @Test
    public void businessCityTest() {
        // TODO: test businessCity
    }

    /**
     * Test the property 'businessPostalCode'
     */
    @Test
    public void businessPostalCodeTest() {
        // TODO: test businessPostalCode
    }

    /**
     * Test the property 'businessCountry'
     */
    @Test
    public void businessCountryTest() {
        // TODO: test businessCountry
    }

    /**
     * Test the property 'businessState'
     */
    @Test
    public void businessStateTest() {
        // TODO: test businessState
    }

    /**
     * Test the property 'vertical'
     */
    @Test
    public void verticalTest() {
        // TODO: test vertical
    }

    /**
     * Test the property 'subVertical'
     */
    @Test
    public void subVerticalTest() {
        // TODO: test subVertical
    }

    /**
     * Test the property 'nameOnBankAccount'
     */
    @Test
    public void nameOnBankAccountTest() {
        // TODO: test nameOnBankAccount
    }

    /**
     * Test the property 'incorporationCountry'
     */
    @Test
    public void incorporationCountryTest() {
        // TODO: test incorporationCountry
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'taxIdNumber'
     */
    @Test
    public void taxIdNumberTest() {
        // TODO: test taxIdNumber
    }

    /**
     * Test the property 'totalAnnualSales'
     */
    @Test
    public void totalAnnualSalesTest() {
        // TODO: test totalAnnualSales
    }

    /**
     * Test the property 'platformName'
     */
    @Test
    public void platformNameTest() {
        // TODO: test platformName
    }

}
