/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetMerchantDetailsResponse
 */
public class GetMerchantDetailsResponseTest {
    private final GetMerchantDetailsResponse model = new GetMerchantDetailsResponse();

    /**
     * Model tests for GetMerchantDetailsResponse
     */
    @Test
    public void testGetMerchantDetailsResponse() {
        // TODO: test GetMerchantDetailsResponse
    }

    /**
     * Test the property 'publicName'
     */
    @Test
    public void publicNameTest() {
        // TODO: test publicName
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'merchantTempId'
     */
    @Test
    public void merchantTempIdTest() {
        // TODO: test merchantTempId
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'merchantStatus'
     */
    @Test
    public void merchantStatusTest() {
        // TODO: test merchantStatus
    }

}
