/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetMerchantResponse
 */
public class GetMerchantResponseTest {
    private final GetMerchantResponse model = new GetMerchantResponse();

    /**
     * Model tests for GetMerchantResponse
     */
    @Test
    public void testGetMerchantResponse() {
        // TODO: test GetMerchantResponse
    }

    /**
     * Test the property 'publicName'
     */
    @Test
    public void publicNameTest() {
        // TODO: test publicName
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'annualSales'
     */
    @Test
    public void annualSalesTest() {
        // TODO: test annualSales
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'merchantTempId'
     */
    @Test
    public void merchantTempIdTest() {
        // TODO: test merchantTempId
    }

}
