/*
 * Splitit.OnBoarding.Api.V2
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.ProcessorResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProcessorsResponse
 */
public class ProcessorsResponseTest {
    private final ProcessorsResponse model = new ProcessorsResponse();

    /**
     * Model tests for ProcessorsResponse
     */
    @Test
    public void testProcessorsResponse() {
        // TODO: test ProcessorsResponse
    }

    /**
     * Test the property 'processors'
     */
    @Test
    public void processorsTest() {
        // TODO: test processors
    }

}
