/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CountryResponse
 */
export interface CountryResponse {
    /**
     * 
     * @type {string}
     * @memberof CountryResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CountryResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CountryResponse
     */
    'isoA2': string;
    /**
     * 
     * @type {string}
     * @memberof CountryResponse
     */
    'isoA3': string;
    /**
     * 
     * @type {string}
     * @memberof CountryResponse
     */
    'isoNumber': string | null;
}

