/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RequestHeaderSlim } from './request-header-slim';

/**
 * 
 * @export
 * @interface CreateDeveloperRequest
 */
export interface CreateDeveloperRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDeveloperRequest
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeveloperRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeveloperRequest
     */
    'companyName': string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDeveloperRequest
     */
    'termsAndConditions': boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateDeveloperRequest
     */
    'countryCode': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeveloperRequest
     */
    'fullCountryName': string;
    /**
     * 
     * @type {RequestHeaderSlim}
     * @memberof CreateDeveloperRequest
     */
    'requestHeader': RequestHeaderSlim;
}

