/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GetMerchantDetailsResponse
 */
export interface GetMerchantDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'publicName': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'legalName': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'phoneNumber': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'merchantTempId': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantDetailsResponse
     */
    'merchantStatus': string;
}

