/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GetMerchantResponse
 */
export interface GetMerchantResponse {
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'legalName': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'annualSales': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof GetMerchantResponse
     */
    'merchantTempId': string;
}

