/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface MerchantVerticalResponse
 */
export interface MerchantVerticalResponse {
    /**
     * 
     * @type {string}
     * @memberof MerchantVerticalResponse
     */
    'verticalDisplayName': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantVerticalResponse
     */
    'verticalSplititName': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MerchantVerticalResponse
     */
    'subCategories': Array<string>;
}

