/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MerchantVerticalResponse } from './merchant-vertical-response';

/**
 * 
 * @export
 * @interface MerchantVerticalsResponse
 */
export interface MerchantVerticalsResponse {
    /**
     * 
     * @type {Array<MerchantVerticalResponse>}
     * @memberof MerchantVerticalsResponse
     */
    'merchantVerticals': Array<MerchantVerticalResponse>;
}

