/* tslint:disable */
/* eslint-disable */
/**
 * Splitit.OnBoarding.Api.V2
 * Splitit\'s Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ResponseHeader
 */
export interface ResponseHeader {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseHeader
     */
    'succeeded': boolean;
    /**
     * 
     * @type {Array<Error>}
     * @memberof ResponseHeader
     */
    'errors'?: Array<Error>;
    /**
     * 
     * @type {string}
     * @memberof ResponseHeader
     */
    'traceId'?: string;
}

