/*
 * Splitit.OnBoarding.Api.V2
 *
 * Splitit's Onboarding API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Splitit.Onboarding.Net.Client;
using Splitit.Onboarding.Net.Api;
// uncomment below to import models
//using Splitit.Onboarding.Net.Model;

namespace Splitit.Onboarding.Net.Test.Api
{
    /// <summary>
    ///  Class for testing MerchantsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MerchantsApiTests : IDisposable
    {
        private MerchantsApi instance;

        public MerchantsApiTests()
        {
            instance = new MerchantsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MerchantsApi
            //Assert.IsType<MerchantsApi>(instance);
        }

        /// <summary>
        /// Test Create
        /// </summary>
        [Fact]
        public void CreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateMerchantRequest createMerchantRequest = null;
            //var response = instance.Create(createMerchantRequest);
            //Assert.IsType<CreateMerchantResponse>(response);
        }

        /// <summary>
        /// Test CreateDeveloper
        /// </summary>
        [Fact]
        public void CreateDeveloperTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateDeveloperRequest createDeveloperRequest = null;
            //var response = instance.CreateDeveloper(createDeveloperRequest);
            //Assert.IsType<CreateMerchantResponse>(response);
        }

        /// <summary>
        /// Test Get
        /// </summary>
        [Fact]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int numberOfRowsInPage = null;
            //int pageNumber = null;
            //string name = null;
            //string legalName = null;
            //int? status = null;
            //var response = instance.Get(numberOfRowsInPage, pageNumber, name, legalName, status);
            //Assert.IsType<GetMerchantsResponse>(response);
        }

        /// <summary>
        /// Test GetDetails
        /// </summary>
        [Fact]
        public void GetDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string merchantTempId = null;
            //var response = instance.GetDetails(merchantTempId);
            //Assert.IsType<GetMerchantDetailsResponse>(response);
        }
    }
}
